name: Run Bun Tests

on:
  # Schedule to run daily at midnight UTC
  schedule:
    - cron: '0 0 * * *'
  # Allow manual triggering of the workflow
  workflow_dispatch:
  push:  
  repository_dispatch:
    types: [publish-trigger]

permissions:
  contents: write

jobs:
  # Move closed issue folders before running tests
  move-closed-issue-folders:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Set up Bun (using canary version)
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      # Install dependencies (Octokit to interact with GitHub API)
      - run: bun install --frozen-lockfile

      # Run the TypeScript script to move folders based on closed issue IDs
      - name: Run folder move script
        run: |
          bun run move-closed-issues.ts

      # Commit the changes if any folders were moved
      - name: Commit changes
        id: commit
        continue-on-error: true
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Move closed issues to 'closed' folder"
          git push

      - name: Trigger Publish Workflow
        uses: actions/github-script@v7
        if: steps.commit.outcome == 'success' && github.event_name == 'push'
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'publish-trigger',
            });

  bun-test:
    runs-on: ${{ matrix.os }}
    needs: move-closed-issue-folders
    strategy:
      fail-fast: false 
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Set up Bun (using canary version)
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: canary

      # Install dependencies
      - name: Install dependencies
        run: bun install --frozen-lockfile

      # Run tests
      - name: Run tests
        run: bun test
